### ISSUE TITLE
1.0.8 breaks flag usage on onSuccess

### ISSUE THREAD

**Issue by nanoxd** [gilamran/tsc-watch#6] opened 2017-08-25 14:51 UTC
Previously with v1.0.7, the following command would work:

`tsc-watch --onSuccess \"node -r dotenv/config dist/index.js\"`

As of 1.0.8 it fails with the following error message:
```
yarn dev v0.27.5
$ tsc-watch --onSuccess "node -r dotenv/config dist/index.js"
env: node\r: No such file or directory
error Command failed with exit code 127.
```

**Comment by fabiob** [comment] 2017-08-27 23:23
Duplicate of #5

**Comment by gilamran** [comment] 2017-12-05 17:22
As @fabiob mentioned it's Duplicate of #5 (Fixed in version 1.0.10)

**Closed by gilamran** 2017-12-05 17:22 UTC
