### ISSUE TITLE
compiler option does not work with yarn 2 (PnP)

### ISSUE THREAD

**Issue by rhyek** [gilamran/tsc-watch#110] opened 2021-01-27 02:55 UTC
I have a typescript monorepo [here](https://github.com/rhyek/typescript-monorepo-example/tree/yarn).

The `dev` script for the `webapi` project is `"tsc-watch --compiler ttypescript/bin/tsc -b tsconfig.build.json --onSuccess \"node --inspect build/main\""`.

It fails with the following:
```
❯ yarn dev
tsc-watch tried to access ttypescript, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: ttypescript (via "ttypescript/bin/tsc")
Required by: tsc-watch@virtual:2ce4383383692e59ea21f70555fc9c7f73641366c3d669241c3ef561ec73a23755745a3aa49cd786680c1a0f55e944f73fba87476ad82a40eca0d4eeb26aa55f#npm:4.2.9 (via /home/carlos/Dev/personal/typescript-monorepo/.yarn/$$virtual/tsc-watch-virtual-c8e1a773d5/0/cache/tsc-watch-npm-4.2.9-f898a4f291-b1c2a2d295.zip/node_modules/tsc-watch/lib/)

Require stack:
- /home/carlos/Dev/personal/typescript-monorepo/.yarn/$$virtual/tsc-watch-virtual-c8e1a773d5/0/cache/tsc-watch-npm-4.2.9-f898a4f291-b1c2a2d295.zip/node_modules/tsc-watch/lib/tsc-watch.js
- /home/carlos/Dev/personal/typescript-monorepo/.yarn/$$virtual/tsc-watch-virtual-c8e1a773d5/0/cache/tsc-watch-npm-4.2.9-f898a4f291-b1c2a2d295.zip/node_modules/tsc-watch/index.js
```

The project and all scripts work fine when using `pnpm`.

**Comment by gilamran** [comment] 2021-01-27 09:25
Did you notice that you wrote `ttypescript` ? double `t`
Maybe that's the issue?

**Comment by rhyek** [comment] 2021-01-27 13:07
no. if I wanted the default typescript compiler why would I be using the compiler option? 😁

**Comment by gilamran** [comment] 2021-02-01 15:31
Can you please create an example repo.? showing this problem

**Comment by rhyek** [comment] 2021-02-01 17:40
bro are you serious? i linked it in the issue description.

**Comment by gilamran** [comment] 2021-02-01 19:32
hoo, somehow I missed it.
Checking

**Comment by gilamran** [comment] 2021-02-01 19:54
I was not able to cause the issue, I'm getting:
```
Scope: 2 of 3 workspace projects
src/webapi dev$ tsc-watch --compiler ttypescript/bin/tsc -b tsconfig.build.json --onSuccess "node --inspect dist/main"
src/webapi dev: sh: tsc-watch: command not found
/Users/gil/projects/typescript-monorepo-example/src/webapi:
 ERROR  webapi@0.0.1 dev: `tsc-watch --compiler ttypescript/bin/tsc -b tsconfig.build.json --onSuccess "node --inspect dist/main"`
spawn ENOENT
```

But as I understand on yarn 2, there's no `node_modules` and if a package is requiring a package that isn't in its dependencies you'll get this error. (`tsc-watch tried to access ttypescript, but it isn't declared in its dependencies`)

I can't add `ttypescript` to the package dependencies, as there can be many compilers...

But I did find in the yarn docs that you can add `packageExtensions` to your `.yarnrc.yml` and "force" my package to have another dependency, something like this:
```
packageExtensions:
  "tsc-watch@*":
    dependencies:
      ttypescript: "*"
```

Please give it a try, as I can't reproduce this. and let me know. I'll add this to the docs.

Thanks

**Comment by rhyek** [comment] 2021-02-11 17:47
Hey, sorry for not responding sooner. I dropped yarn 2 and went with a different package manager (pnpm). I'm not able to test  your solution with yarn soon. Feel free to close, thanks.

**Comment by merceyz** [comment] 2021-02-11 18:59
Feel free to assign this to me, i'll get around to fixing it either way but doesn't hurt to document. It's a bug in general unrelated to Yarn PnP but to reproduce it without PnP isn't the most straight forward thing to do

**Closed** 2021-05-26 10:33 UTC
