### ISSUE TITLE
node\r: No such file or directory v4.2.0

### ISSUE THREAD

**Issue by ktjd123** [gilamran/tsc-watch#82] opened 2020-02-29 17:08 UTC
log

yarn run v1.21.1
$ rm -rf bin && cross-env NODE_ENV=development tsc-watch -p tsconfig.json
env: node\r: No such file or directory
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

changing to 4.1.0 works great.

node v12.16.1

**Comment by gilamran** [comment] 2020-02-29 19:55
@ktjd123 
I'm trying to gather information about your issue.
What does the command `yarn run v1.21.1` suppose to do? can you share your "scripts" section of your `package.json`?

Also, can you please try version 4.2.2 (Just release) and let me know if it fixed the issue?

Thanks

**Comment by sat0yu** [comment] 2020-03-01 02:18
I've run into the same problem when using `tsc-watch@4.2.0`

Here's an example repo to reproduce the error
https://github.com/sat0yu/tsc-watch-4.2.0

```sh
% docker-compose up --build tsc-watch
Starting tsc-watch-420_tsc-watch_1 ... done
Attaching to tsc-watch-420_tsc-watch_1
tsc-watch_1  | yarn install v1.19.2
tsc-watch_1  | [1/4] Resolving packages...
tsc-watch_1  | [2/4] Fetching packages...
tsc-watch_1  | [3/4] Linking dependencies...
tsc-watch_1  | [4/4] Building fresh packages...
tsc-watch_1  | Done in 6.00s.
tsc-watch_1  | yarn run v1.19.2
tsc-watch_1  | $ tsc-watch --onSuccess "yarn node dist/index.js"
tsc-watch_1  | /usr/bin/env: 'node\r': No such file or directory
tsc-watch_1  | error Command failed with exit code 127.
tsc-watch_1  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
tsc-watch-420_tsc-watch_1 exited with code 127
```

**Comment by ktjd123** [comment] 2020-03-01 13:26
the script is

```json
    cross-env NODE_ENV=development tsc-watch -p tsconfig.json --onSuccess \"node build/index.js
```

and tsconfig is
```json
{
  "compilerOptions": {
    "outDir": "./build",
    "allowJs": true,
    "target": "esnext",
    "lib": ["es2015", "es2016", "es2017", "es2018", "dom"],
    "module": "commonjs",
    "moduleResolution": "node",
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noImplicitAny": true,
    "downlevelIteration": true,
    "sourceMap": true,
    "typeRoots": ["./@types", "./node_modules/@types"],
    "baseUrl": "./",
    "alwaysStrict": true,
    "paths": {
      "*": ["@types/*"]
    },
    "strict": true,
    "removeComments": true,
    "experimentalDecorators": true,
    "esModuleInterop": true,
    "jsx": "preserve",
    "isolatedModules": true,
    "noEmit": false,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true,
    "resolveJsonModule": true
  },
  "include": ["./**/*"],
  "exclude": ["./node_modules", "./build", "./.next"]
}
```

for 4.2.2, it's not fixed yet.

Thank you, always appreciate your work

**Comment by gilamran** [comment] 2020-03-01 14:25
Fixed on version 4.2.3
For anyone who counter this:
the execution file uses CRLF instead of LF

**Closed by gilamran** 2020-03-01 14:25 UTC

**Comment by axelander** [comment] 2020-05-13 19:50
@gilamran This seems to be an issue on 4.2.4 too. Manually changing from CRLF to LF on package.json, index.js and lib/tsc-watch.js works. Could it be that the issue has reoccured?

**Comment by gilamran** [comment] 2020-05-13 22:21
yea, happened again.
sorry.
Fixed on 4.2.5

**Comment by decipher-cs** [comment] 2023-04-29 10:12
I faced the same error with version 6.0.1
`yarn add -D tsc-watch@6.0.0` works without any errors so I downgraded.

@gilamran I suspect the recent update broke the package again.

**Comment by gilamran** [comment] 2023-04-29 10:22
Sorry for the issue (Windows....) I fixed it on 6.0.2, can you please retry?

**Comment by decipher-cs** [comment] 2023-04-29 10:26
same error on `"tsc-watch": "^6.0.2"`

**Comment by gilamran** [comment] 2023-04-29 10:42
Please retry, I missed one of the files.
I'll automate this so it wont happen again.

**Comment by decipher-cs** [comment] 2023-04-29 10:49
Fixed on `"tsc-watch": "^6.0.3"`
:+1:

**Comment by gilamran** [comment] 2023-04-29 10:51
And now automated on 6.0.4! wont happen again (I hope)
Please also verify version 6.0.4

**Comment by decipher-cs** [comment] 2023-04-29 10:53
> Please also verify version 6.0.4

`npx tsc-watch` works on `"tsc-watch": "^6.0.4"`
